### ISSUE TITLE
Unable to create the cache directory (Local)

### ISSUE THREAD

**Issue by pvaass** [GoogleCloudPlatform/appengine-symfony-starter-project#6]
I can't get symfony to work because of the following error:

```
Unable to create the cache directory (gs://testing/symfony/cache)
```

php.ini

```
google_app_engine.allow_include_gs_buckets="testing"
```

app.yaml

```
env_variables:
  GCS_BUCKET_NAME: "testing"
  CURRENT_VERSION_ID: "0.0.1"
  CACHE_DIR: "gs://#default#/symfony/cache"
  LOG_DIR: "gs://#default#/symfony/log"
```

Using the latest version of this repository and latest version of AppEngine on Linux. GAE is loaded, verified by calling `get_loaded_extensions`.
I'm running AppEngine locally with the following command:

```
/home/vagrant/google_appengine/dev_appserver.py --php_executable_path=/bin/php-cgi --php_gae_extension_path=/usr/lib64/php/modules/gae_runtime_module.so --admin_host=0.0.0.0 --host=0.0.0.0 /vagrant/www
```

Can someone please help?
